In [1]:
import numpy as np

In [2]:
arr = np.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [3]:
print(arr)

[10 21 32 43 48 15 76 57 89]


In [4]:
type(arr)

numpy.ndarray

In [7]:
arr.shape #mostra a dimensão da array

(9,)

In [8]:
arr[4]

48

In [9]:
arr[1:4]

array([21, 32, 43])

In [10]:
arr[1:4+1]

array([21, 32, 43, 48])

In [12]:
indices = [1, 2, 5, 6]

In [13]:
arr[indices]

array([21, 32, 15, 76])

In [14]:
mask = (arr % 2  ==0)

In [15]:
print(mask)

[ True False  True False  True False  True False False]


In [16]:
arr[mask]

array([10, 32, 48, 76])

In [18]:
arr[0] = 100

In [19]:
print(arr)

[100  21  32  43  48  15  76  57  89]


In [21]:
try:
    arr[0] = 'String'
except:
    print('ação impossível')

ação impossível


In [22]:
arr.cumsum() #soma acumulada

array([100, 121, 153, 196, 244, 259, 335, 392, 481])

In [23]:
arr.cumprod() #produto acumulado

array([       100,       2100,      67200,    2889600,  138700800,
       2080512000, -794877952, 1936596992,  558440448])

In [24]:
arr2 = np.arange(0, 50, 5)

In [25]:
print(arr2)

[ 0  5 10 15 20 25 30 35 40 45]


In [26]:
np.shape(arr2)

(10,)

In [28]:
type(arr2)

numpy.ndarray

In [29]:
arr3 = np.zeros(10)

In [30]:
print(arr3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [31]:
arr4 = np.eye(3) #retorna 1 nas posições em diagonal e 0 no resto

In [32]:
print(arr4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
arr6 = np.diag(np.array([1, 2, 3, 4]))

In [34]:
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [35]:
arr7 = np.array([True, False, True, False])

In [36]:
print(arr7)

[ True False  True False]


In [37]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [38]:
np.linspace(0, 10, 15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [39]:
np.logspace(0, 5, 10)

array([1.00000000e+00, 3.59381366e+00, 1.29154967e+01, 4.64158883e+01,
       1.66810054e+02, 5.99484250e+02, 2.15443469e+03, 7.74263683e+03,
       2.78255940e+04, 1.00000000e+05])